### ISSUE TITLE
Program crashes when taking a screenshot

### ISSUE THREAD

**Issue by yaccos** [biosustain/shu#40]
I tried the most recent functionality of SVG export and found using this functionality to crash the program. Here is the terminal printout when I opened Shu with the default map and tried exporting the view as a SVG file named "map.svg":

```
2023-11-01T00:19:25.230347Z  INFO bevy_winit::system: Creating new window "shu" (0v0)
2023-11-01T00:19:25.362310Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) Iris(R) Xe Graphics", vendor: 32902, device: 42913, device_type: IntegratedGpu, driver: "Intel Corporation", driver_info: "Intel driver", backend: Vulkan }
2023-11-01T00:19:25.386555Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: C:\Users\uqjpette\OneDrive - The University of Queensland\shu\target\release\assets\fonts/FiraSans-Bold.tttx
2023-11-01T00:19:25.386937Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: C:\Users\uqjpette\OneDrive - The University of Queensland\shu\target\release\assets\fonts/Assistant-Regular.tttx
2023-11-01T00:19:25.708704Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Education", kernel: "22621", cpu: "13th Gen Intel(R) Core(TM) i5-1345U", core_count: "10", memory: "31.7 GiB" }
2023-11-01T00:19:38.954059Z  INFO shu::info: msg="Writing SVG..."
thread 'Compute Task Pool (4)' panicked at src\screenshot.rs:159:75:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library\core\src\panicking.rs:72
   2: core::panicking::panic
             at /rustc/31bc7e2c47e82798a392c770611975a6883132c8/library\core\src\panicking.rs:127
   3: core::ops::function::FnMut::call_mut
   4: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
   5: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
   6: async_task::raw::RawTask<F,T,S,M>::run
   7: futures_lite::future::block_on
   8: futures_lite::future::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `shu::screenshot::save_svg_file`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

**Comment by carrascomj** [comment]
Oh, I forgot to add those fonts. Once the CI pass, I'll make a new release.

**Comment by carrascomj** [comment]
It should be fine now (https://github.com/biosustain/shu/releases/tag/0.8.1), feel free to reopen if the problem persists!
